/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import qrcodeGenerator from "strapi-plugin-qrcode-generator/strapi-admin";
import customQrCodeGenerator from "../../src/plugins/custom-qr-code-generator/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "qrcode-generator": qrcodeGenerator,
    "custom-qr-code-generator": customQrCodeGenerator,
  },
});
